run:
  go: 1.21
  timeout: 10m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*conversion.*\\.go$"
  allow-parallel-runners: true

output:
  format: checkstyle:build/reports/golangci-lint-report.xml,colored-line-number

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    #    - bodyclose
    #    - depguard
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    #    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gomodguard:
    blocked:
      modules:
        - k8s.io/klog/v2:
            recommendations:
              - github.com/go-logr/logr
        - google.golang.org/genproto:
            recommendations:
              - google.golang.org/protobuf
              - google.golang.org/grpc
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
        - github.com/gogo/protobuf:
            recommendations:
              - google.golang.org/protobuf
        - gopkg.in/yaml.v2:
            recommendations:
              - sigs.k8s.io/yaml
        - gopkg.in/yaml.v3:
            recommendations:
              - sigs.k8s.io/yaml
        - github.com/pkg/errors:
            reason: "Use errors.New(...) or fmt.Errorf(...)"
  goimports:
    local-prefixes: orltom.dev/golang-http-example/
  stylecheck:
    go: "1.21"
  gosimple:
    go: "1.21"
  staticcheck:
    go: "1.21"
  revive:
    ignore-generated-header: true
    severity: warning
    enable-all-rules: false
    confidence: 0.1
    rules:
      - name: early-return
      - name: error-strings
      - name: unexported-return
      - name: unused-parameter
      - name: use-any
      - name: deep-exit
      - name: empty-lines
      - name: imports-blacklist
  gci:
    sections:
      - standard
      - default
      - prefix(orltom.dev)
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - unused
        - deadcode
      text: is unused
